# Generated by Django 6.0.3 on 2026-04-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_tintuc_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoiTacB2B",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_cong_ty",
                    models.CharField(
                        max_length=200, verbose_name="Tên Công Ty / Cá Nhân"
                    ),
                ),
                (
                    "so_dien_thoai",
                    models.CharField(max_length=15, verbose_name="Số điện thoại"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email liên hệ",
                    ),
                ),
                (
                    "nhu_cau",
                    models.CharField(max_length=200, verbose_name="Nhu cầu hợp tác"),
                ),
                (
                    "ghi_chu_admin",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ghi chú của Admin"
                    ),
                ),
                ("ngay_gui", models.DateTimeField(auto_now_add=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("moi", "Mới tiếp nhận"),
                            ("da_lien_he", "Đã liên hệ tư vấn"),
                            ("dang_dam_phan", "Đang đàm phán"),
                            ("thanh_cong", "Ký hợp đồng thành công"),
                            ("that_bai", "Hủy / Từ chối"),
                        ],
                        default="moi",
                        max_length=20,
                        verbose_name="Trạng thái xử lý",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu cầu Hợp tác",
                "verbose_name_plural": "Quản lý Hợp tác B2B",
            },
        ),
        migrations.CreateModel(
            name="HoSoUngVien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vi_tri_ung_tuyen",
                    models.CharField(max_length=100, verbose_name="Vị trí ứng tuyển"),
                ),
                ("ho_ten", models.CharField(max_length=100, verbose_name="Họ và tên")),
                (
                    "so_dien_thoai",
                    models.CharField(max_length=15, verbose_name="Số điện thoại"),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "file_cv",
                    models.FileField(
                        upload_to="cv_ung_vien/", verbose_name="File CV (PDF/Word)"
                    ),
                ),
                ("ngay_nop", models.DateTimeField(auto_now_add=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("moi", "Hồ sơ mới"),
                            ("dang_xem", "Đang xem xét"),
                            ("phong_van", "Hẹn phỏng vấn"),
                            ("nhan_viec", "Đã nhận việc"),
                            ("tu_choi", "Không phù hợp"),
                        ],
                        default="moi",
                        max_length=20,
                        verbose_name="Trạng thái hồ sơ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ Ứng viên",
                "verbose_name_plural": "Quản lý Tuyển dụng",
            },
        ),
        migrations.CreateModel(
            name="LienHeGopY",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ho_ten",
                    models.CharField(
                        max_length=100, verbose_name="Họ và tên khách hàng"
                    ),
                ),
                (
                    "so_dien_thoai",
                    models.CharField(max_length=15, verbose_name="Số điện thoại"),
                ),
                ("tieu_de", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                (
                    "noi_dung",
                    models.TextField(verbose_name="Nội dung góp ý / thắc mắc"),
                ),
                ("ngay_gui", models.DateTimeField(auto_now_add=True)),
                (
                    "da_xu_ly",
                    models.BooleanField(
                        default=False, verbose_name="Đã xử lý / Gọi lại?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Liên hệ / Góp ý",
                "verbose_name_plural": "Quản lý Góp ý Khách hàng",
            },
        ),
    ]
