# Generated by Django 6.0.3 on 2026-04-08 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_danhmucmart_sanphammart"),
    ]

    operations = [
        migrations.CreateModel(
            name="DanhGiaSanPham",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_khach_hang",
                    models.CharField(max_length=100, verbose_name="Tên khách hàng"),
                ),
                ("so_sao", models.IntegerField(default=5, verbose_name="Số sao (1-5)")),
                ("noi_dung", models.TextField(verbose_name="Nội dung đánh giá")),
                ("ngay_gui", models.DateTimeField(auto_now_add=True)),
                (
                    "da_duyet",
                    models.BooleanField(
                        default=False, verbose_name="Đã duyệt (Cho phép hiện lên Web)"
                    ),
                ),
                (
                    "san_pham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cac_danh_gia",
                        to="core.sanpham",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đánh giá Sản phẩm",
                "verbose_name_plural": "Quản lý Đánh giá",
            },
        ),
    ]
