# Generated by Django 6.0.3 on 2026-04-16 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_danhgiatram_delete_danhgiasanpham"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoadon",
            name="email_nhan_hd",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hoadon",
            name="ma_so_thue",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hoadon",
            name="ten_cong_ty",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hoadon",
            name="yeu_cau_vat",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CaLamViec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thoi_gian_bat_dau", models.DateTimeField(auto_now_add=True)),
                ("thoi_gian_ket_thuc", models.DateTimeField(blank=True, null=True)),
                (
                    "tien_dau_ca",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("so_loc_dau_ca", models.FloatField(default=0)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("dang_mo", "Đang mở"), ("da_chot", "Đã chốt")],
                        default="dang_mo",
                        max_length=20,
                    ),
                ),
                (
                    "nhan_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tram",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tramxang",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NopTienGiuaCa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_tien", models.DecimalField(decimal_places=0, max_digits=12)),
                ("nguoi_nhan", models.CharField(max_length=100)),
                ("thoi_gian", models.DateTimeField(auto_now_add=True)),
                (
                    "ca_lam_viec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cac_lan_nop",
                        to="core.calamviec",
                    ),
                ),
            ],
        ),
    ]
