# Generated by Django 6.0.3 on 2026-04-16 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_hoadon_email_nhan_hd_hoadon_ma_so_thue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calamviec",
            name="tong_so_lit_ban",
            field=models.FloatField(default=0, verbose_name="Tổng số lít đã bán"),
        ),
        migrations.AddField(
            model_name="calamviec",
            name="tong_tien_thu",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Tổng doanh thu ca",
            ),
        ),
        migrations.AddField(
            model_name="hoadon",
            name="ca_lam_viec",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_hoa_don",
                to="core.calamviec",
                verbose_name="Thuộc Ca Làm Việc",
            ),
        ),
        migrations.AlterField(
            model_name="calamviec",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("dang_mo", "Đang làm việc"),
                    ("cho_duyet", "Đã chốt - Chờ nộp tiền"),
                    ("da_chot", "Đã nộp tiền & Hoàn tất"),
                ],
                default="dang_mo",
                max_length=20,
            ),
        ),
    ]
