# Generated by Django 6.0.1 on 2026-04-29 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_calamviec_tong_so_lit_ban_calamviec_tong_tien_thu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="danhgiatram",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
