# Generated by Django 6.0.1 on 2026-04-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_danhgiatram_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Giám đốc / Quản trị viên"),
                    ("ke_toan", "Kế toán nội bộ"),
                    ("truong_tram", "Cửa hàng trưởng / Trưởng trạm"),
                    ("nv_ban_xang", "Nhân viên bơm xăng"),
                    ("khach_hang", "Khách hàng Google"),
                ],
                default="khach_hang",
                max_length=20,
                verbose_name="Chức vụ",
            ),
        ),
    ]
