# Generated by Django 6.0.3 on 2026-04-08 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_doitacb2b_hosoungvien_lienhegopy"),
    ]

    operations = [
        migrations.CreateModel(
            name="DanhMucMart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_danh_muc",
                    models.CharField(
                        max_length=100,
                        verbose_name="Tên Danh Mục (VD: Nước uống, Đồ ăn nhanh)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danh mục Mart",
                "verbose_name_plural": "Danh mục Mart",
            },
        ),
        migrations.CreateModel(
            name="SanPhamMart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_san_pham",
                    models.CharField(max_length=100, verbose_name="Tên sản phẩm"),
                ),
                ("gia_ban", models.FloatField(verbose_name="Giá bán (VNĐ)")),
                (
                    "ton_kho",
                    models.IntegerField(default=0, verbose_name="Số lượng tồn kho"),
                ),
                (
                    "anh_san_pham",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="mart/",
                        verbose_name="Ảnh minh họa",
                    ),
                ),
                (
                    "danh_muc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.danhmucmart",
                        verbose_name="Thuộc danh mục",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm Mart",
                "verbose_name_plural": "Sản phẩm Mart",
            },
        ),
    ]
